---
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add execution permissions to testme.sh.
      run: chmod +x testme.sh

    - name: Execute tests.
      run: sudo /bin/bash -H -c './testme.sh -i -k'